// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4SfXKth_cJTKiQs208n1Ix5XwsPlhC4',
    appId: '1:226949932814:web:643eec8a5c78974970995f',
    messagingSenderId: '226949932814',
    projectId: 'tunedheartz',
    authDomain: 'tunedheartz.firebaseapp.com',
    storageBucket: 'tunedheartz.appspot.com',
    measurementId: 'G-Q24MM8FC9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1JDt3PMv2ClKWli_bqpKDhe89MYX7xL4',
    appId: '1:226949932814:android:940888ade5b10b7d70995f',
    messagingSenderId: '226949932814',
    projectId: 'tunedheartz',
    storageBucket: 'tunedheartz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvXnbZtuYK8xcNac8hmfXJ5N5VdYrF8sg',
    appId: '1:226949932814:ios:eb42b966375625c370995f',
    messagingSenderId: '226949932814',
    projectId: 'tunedheartz',
    storageBucket: 'tunedheartz.appspot.com',
    iosBundleId: 'com.example.tunedheartz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvXnbZtuYK8xcNac8hmfXJ5N5VdYrF8sg',
    appId: '1:226949932814:ios:6f26538170ae82c570995f',
    messagingSenderId: '226949932814',
    projectId: 'tunedheartz',
    storageBucket: 'tunedheartz.appspot.com',
    iosBundleId: 'com.example.tunedheartz.RunnerTests',
  );
}
