// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbopE8Kq-u5bNwxYNhVe5DZCueEnScRk',
    appId: '1:99776041967:web:31dae88968d9073f26dc1a',
    messagingSenderId: '99776041967',
    projectId: 'tunedheartz-2b42c',
    authDomain: 'tunedheartz-2b42c.firebaseapp.com',
    storageBucket: 'tunedheartz-2b42c.appspot.com',
    measurementId: 'G-RRLVENXVYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjpYwSlK4uGWYrWJh0z-o8OHsmYPaBaBo',
    appId: '1:99776041967:android:c544a175e0fcb04e26dc1a',
    messagingSenderId: '99776041967',
    projectId: 'tunedheartz-2b42c',
    storageBucket: 'tunedheartz-2b42c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD81wG8kj5cRInVF8PJgRxFLvi3f0IRoU0',
    appId: '1:99776041967:ios:1c9e807b999ccb2526dc1a',
    messagingSenderId: '99776041967',
    projectId: 'tunedheartz-2b42c',
    storageBucket: 'tunedheartz-2b42c.appspot.com',
    iosBundleId: 'com.example.tunedheartz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD81wG8kj5cRInVF8PJgRxFLvi3f0IRoU0',
    appId: '1:99776041967:ios:63de3edb71c9b2ff26dc1a',
    messagingSenderId: '99776041967',
    projectId: 'tunedheartz-2b42c',
    storageBucket: 'tunedheartz-2b42c.appspot.com',
    iosBundleId: 'com.example.tunedheartz.RunnerTests',
  );
}
